# AUTO-GENERATED by Agent Import System — Phase 1 thin-wrapper scaffold
# Plugin ID      : simple_qa
# External graph : agent.graph
# Strategy       : thin_wrapper
#
# The external graph runs untouched inside a single LangGraph node.
# Its state is translated to/from the CommonState envelope here.
# Re-run import to regenerate, or edit freely for custom behaviour.

from __future__ import annotations

import json
import logging
import operator
import os
import sys
from typing import Annotated, Any, Dict, List, Optional

from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict

# ── Ensure the external source (copied into src/) is importable ───────────────
_SRC_DIR = os.path.join(os.path.dirname(__file__), "src")
if _SRC_DIR not in sys.path:
    sys.path.insert(0, _SRC_DIR)

from agent import graph as _external_graph  # noqa: E402

logger = logging.getLogger(__name__)

# ── A2UI screen definitions (Phase 1 defaults; replaced by LLM in Phase 2) ────
_SCREENS = {
    "collecting": {
        "components": [
            {
                "children": [
                    "processing_text",
                    "progress"
                ],
                "component": "Column",
                "id": "root"
            },
            {
                "component": "Text",
                "data": {
                    "variant": "h2"
                },
                "id": "processing_text",
                "text": "Finding the best answer for you..."
            },
            {
                "component": "ProgressBar",
                "data": {
                    "label": "Processing",
                    "value": 50
                },
                "id": "progress"
            }
        ],
        "title": "Processing Your Question",
        "voice_text": "I\u0027m thinking about your question. Please wait a moment."
    },
    "error": {
        "components": [
            {
                "children": [
                    "error_alert",
                    "retry_btn"
                ],
                "component": "Column",
                "id": "root"
            },
            {
                "component": "BenefitCard",
                "data": {
                    "detail": "I encountered an issue processing your question. Please try rephrasing it or ask something else."
                },
                "id": "error_alert",
                "text": "Error",
                "variant": "Warning"
            },
            {
                "component": "Button",
                "data": {
                    "action": "simple_qa.retry_question"
                },
                "id": "retry_btn",
                "text": "Try Again"
            }
        ],
        "title": "Something Went Wrong",
        "voice_text": "I\u0027m sorry, I couldn\u0027t process your question. Please try again."
    },
    "result": {
        "components": [
            {
                "children": [
                    "answer_card",
                    "action_row"
                ],
                "component": "Column",
                "id": "root"
            },
            {
                "component": "DataCard",
                "data": {
                    "detail": "{response}"
                },
                "id": "answer_card",
                "text": "Answer"
            },
            {
                "children": [
                    "ask_again_btn",
                    "help_btn"
                ],
                "component": "Row",
                "id": "action_row"
            },
            {
                "component": "Button",
                "data": {
                    "action": "simple_qa.ask_question"
                },
                "id": "ask_again_btn",
                "text": "Ask Another Question"
            },
            {
                "component": "Button",
                "data": {
                    "action": "simple_qa.get_help"
                },
                "id": "help_btn",
                "text": "Get Help"
            }
        ],
        "title": "Your Answer",
        "voice_text": "Here\u0027s the answer to your question: {response}"
    },
    "welcome": {
        "components": [
            {
                "children": [
                    "greeting_text",
                    "input_prompt"
                ],
                "component": "Column",
                "id": "root"
            },
            {
                "component": "Text",
                "data": {
                    "variant": "h1"
                },
                "id": "greeting_text",
                "text": "Simple Q\u0026A Assistant"
            },
            {
                "component": "Text",
                "data": {
                    "variant": "body"
                },
                "id": "input_prompt",
                "text": "Ask me anything and I\u0027ll do my best to help."
            }
        ],
        "title": "Ask a Question",
        "voice_text": "Welcome to Simple Q\u0026A. Please ask your question and I\u0027ll provide an answer."
    }
}


# ── CommonState TypedDict (must match contracts.CommonState) ──────────────────

class WrappedState(TypedDict, total=False):
    mode: str
    device: str
    transcript: str
    messages: Annotated[List[Dict[str, Any]], operator.add]
    ui: Dict[str, Any]
    errors: Optional[Dict[str, Any]]
    pendingAction: Optional[Dict[str, Any]]
    outbox: Annotated[List[Dict[str, Any]], operator.add]
    meta: Dict[str, Any]
    domain: Dict[str, Any]
    state_version: int


# ── A2UI helpers ───────────────────────────────────────────────────────────────

def _a2ui_patch(components: list, title: str) -> Dict[str, Any]:
    return {
        "type": "server.a2ui.patch",
        "payload": {
            "updateComponents": {"components": components},
            "title": title,
        },
    }


def _render_screen(screen_key: str, response: str = "") -> list:
    """
    Return outbox events for a given screen key.
    '{response}' placeholders in voice_text and DataCard detail are substituted.
    """
    screen = _SCREENS.get(screen_key, _SCREENS.get("result", {}))
    components = screen.get("components", [])
    voice_text = screen.get("voice_text", response).replace("{response}", response)
    title = screen.get("title", "Response")

    # Deep-substitute {response} in component data fields
    components_rendered = json.loads(
        json.dumps(components).replace("{response}", response.replace('"', '\\"'))
    )

    events = [_a2ui_patch(components_rendered, title)]
    if voice_text:
        events.append({"type": "server.voice.say", "payload": {"text": voice_text[:300]}})
        events.append({
            "type": "server.transcript.final",
            "payload": {"text": voice_text, "role": "assistant"},
        })
    return events


# ── Graph nodes ────────────────────────────────────────────────────────────────

def handle_welcome(state: WrappedState) -> dict:
    """Emit the welcome screen when no transcript is present."""
    return {"outbox": _render_screen("welcome")}


def run_external_graph(state: WrappedState) -> dict:
    """
    Translate CommonState → external state, invoke the external graph,
    translate the result back to outbox events.
    """
    transcript = (state.get("transcript") or "").strip()

    # ── Input translation ────────────────────────────────────────────────────
    from langchain_core.messages import HumanMessage
    ext_input = {"messages": [HumanMessage(transcript)]}

    # ── Invoke ───────────────────────────────────────────────────────────────
    try:
        ext_result = _external_graph.invoke(ext_input)
    except Exception as exc:
        logger.error("[simple_qa] External graph error: %s", exc)
        return {"outbox": _render_screen("error")}

    # ── Output translation ───────────────────────────────────────────────────
    try:
        _msgs = ext_result.get("messages", [])
        response = _msgs[-1].content if _msgs else ""
    except Exception:
        response = str(ext_result)

    return {"outbox": _render_screen("result", response=response)}


def handle_default(state: WrappedState) -> dict:
    """Catch-all fallback."""
    return {"outbox": _render_screen("error")}


def clear_pending_action(state: WrappedState) -> dict:
    return {"pendingAction": None, "transcript": ""}


# ── Router ─────────────────────────────────────────────────────────────────────

def start_router(state: WrappedState) -> str:
    transcript = (state.get("transcript") or "").strip()
    if not transcript:
        return "handle_welcome"
    return "run_external_graph"


# ── Graph assembly ─────────────────────────────────────────────────────────────

builder = StateGraph(WrappedState)

builder.add_node("handle_welcome",       handle_welcome)
builder.add_node("run_external_graph",   run_external_graph)
builder.add_node("handle_default",       handle_default)
builder.add_node("clear_pending_action", clear_pending_action)

# START → router decides which handler to call
builder.add_conditional_edges(
    START,
    start_router,
    {
        "handle_welcome":     "handle_welcome",
        "run_external_graph": "run_external_graph",
    },
)

builder.add_edge("handle_welcome",      "clear_pending_action")
builder.add_edge("run_external_graph",  "clear_pending_action")
builder.add_edge("handle_default",      "clear_pending_action")
builder.add_edge("clear_pending_action", END)

app_graph = builder.compile()
