# AUTO-GENERATED by Agent Import System — Phase 1 scaffold
# Plugin ID : simple_qa
# Re-run import to regenerate, or edit freely for custom behaviour.

from __future__ import annotations

from typing import Any, Dict

from app.agent.core.contracts import PluginBase


class SimpleQaPlugin(PluginBase):

    @property
    def plugin_id(self) -> str:
        return "simple_qa"

    def build_graph(self):
        from app.agent.plugins.simple_qa.graph import app_graph
        return app_graph

    def create_initial_state(self) -> Dict[str, Any]:
        return {
            # ── CommonState envelope ──────────────────────────────────────────
            "mode": "text",
            "device": "desktop",
            "transcript": "",
            "messages": [],
            "ui": {"surfaceId": "main", "state": "LOADING"},
            "errors": None,
            "pendingAction": None,
            "outbox": [],
            "meta": {},
            "state_version": self.state_version,
            # ── Domain data ───────────────────────────────────────────────────
            "domain": {
                "simple_qa": {},
            },
        }

    @property
    def capabilities(self) -> Dict[str, Any]:
        return {
            "voice_greeting": "Welcome to Simple Q&A. Please ask your question and I'll provide an answer.",
            "supported_components": ["Column", "Row", "DataCard", "Button"],
            "readme_excerpt": "# Simple Q\u0026A Agent\n\nA minimal LangGraph agent for testing the A2UI import wizard.\n\nThis agent receives a user question via `messages` (a `List[BaseMessage]`) and\nreturns a plain-text answer in the same list.  It uses the standard\n`messages`-based state so the **Thin Wrapper** strategy works out of the box.\n\n## How to import\n\n1. Start the A2UI server and client (`./manage.sh start`)\n2. Open `http://localhost:3000/transfer`\n3. Paste the absolute path to this directory, e.g.:\n   `/path/to/A2UI_S2S/test-agents/simple_qa`\n4. Set plugin ID: `simple_qa`\n5. Keep strategy as **Thin Wrapper**\n6. Click *",
        }
